#!/usr/bin/env bash
# install.sh — deploy webTraffik on a Linux host (no Go/make required)
#
# Usage:
#   1. scp the correct binary alongside this script AND firewall.sh + nftables.conf:
#        scp dist/webtraffik_linux_amd64 user@host:webtraffik
#        scp install.sh firewall.sh nftables.conf user@host:
#   2. On the remote host:
#        sudo bash install.sh [BINARY]
#
#   BINARY defaults to ./webtraffik if not specified.
#   Run with sudo or as root.

set -euo pipefail

BINARY_SRC="${1:-./webtraffik}"
INSTALL_BIN="/usr/local/bin/webtraffik"
DATA_DIR="/var/lib/webtraffik"
CONFIG_DIR="/etc/webtraffik"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
SERVICE_FILE="/etc/systemd/system/webtraffik.service"
SERVICE_USER="webtraffik"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Sanity checks ─────────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
  echo "error: run this script as root (sudo bash install.sh)" >&2
  exit 1
fi

if [[ ! -f "$BINARY_SRC" ]]; then
  echo "error: binary not found: $BINARY_SRC" >&2
  echo "       scp the correct dist binary to this host first, then re-run." >&2
  exit 1
fi

if ! command -v systemctl &>/dev/null; then
  echo "error: systemd not found — this script requires a systemd-based Linux host" >&2
  exit 1
fi

# ── Create system user ────────────────────────────────────────────────────────

if id "$SERVICE_USER" &>/dev/null; then
  echo "user '$SERVICE_USER' already exists — skipping"
else
  useradd --system --no-create-home \
          --home "$DATA_DIR" \
          --shell /usr/sbin/nologin \
          "$SERVICE_USER"
  echo "created system user: $SERVICE_USER"
fi

# ── Data directory ────────────────────────────────────────────────────────────

install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 755 "$DATA_DIR"
echo "data directory: $DATA_DIR"

# ── Config directory ──────────────────────────────────────────────────────────

install -d -o root -g "$SERVICE_USER" -m 750 "$CONFIG_DIR"
if [[ ! -f "$CONFIG_FILE" ]]; then
  if [[ -f "${SCRIPT_DIR}/config.yaml.example" ]]; then
    install -m 640 -o root -g "$SERVICE_USER" "${SCRIPT_DIR}/config.yaml.example" "$CONFIG_FILE"
  else
    printf '# webTraffik configuration — see config.yaml.example in the repository.\n' > "$CONFIG_FILE"
    chown root:"$SERVICE_USER" "$CONFIG_FILE"; chmod 640 "$CONFIG_FILE"
  fi
  echo "wrote default config: $CONFIG_FILE"

  # Secure by default: protect the dashboard with a generated password.
  PASS_FILE="$CONFIG_DIR/dashboard.pass"
  DASH_PASS="$(head -c 24 /dev/urandom | base64 | tr -d '/+=\n' | head -c 24)"
  printf '%s\n' "$DASH_PASS" > "$PASS_FILE"
  chown root:"$SERVICE_USER" "$PASS_FILE"; chmod 640 "$PASS_FILE"
  {
    echo ""
    echo "# ── Generated by install.sh ─────────────────────────────────────────────"
    echo "dashboard-user: admin"
    echo "dashboard-pass-file: $PASS_FILE"
  } >> "$CONFIG_FILE"
  GENERATED_PASS="$DASH_PASS"
else
  echo "config already exists — skipping: $CONFIG_FILE"
fi

# ── Install binary ────────────────────────────────────────────────────────────

install -m 755 "$BINARY_SRC" "$INSTALL_BIN"
echo "installed binary: $INSTALL_BIN"

# Older versions installed a BTF helper that is no longer needed.
rm -rf /usr/local/lib/webtraffik

# ── Install systemd service unit ──────────────────────────────────────────────

UNIT_SRC="${SCRIPT_DIR}/webtraffik.service"
if [[ ! -f "$UNIT_SRC" ]]; then
  echo "error: webtraffik.service not found alongside install.sh" >&2
  exit 1
fi
install -m 644 "$UNIT_SRC" "$SERVICE_FILE"
echo "installed service unit: $SERVICE_FILE"

# ── Firewall ──────────────────────────────────────────────────────────────────

FIREWALL_SH="${SCRIPT_DIR}/firewall.sh"
if [[ -f "$FIREWALL_SH" ]]; then
  echo ""
  echo "── Configuring firewall ──────────────────────────────────────────────────"
  bash "$FIREWALL_SH"
else
  echo "warning: firewall.sh not found alongside install.sh — skipping firewall setup" >&2
  echo "         Copy firewall.sh and nftables.conf next to install.sh and re-run to apply." >&2
fi

# ── Enable and restart (or start) services ────────────────────────────────────

echo ""
echo "── Starting services ─────────────────────────────────────────────────────"

systemctl daemon-reload
systemctl enable webtraffik.service

if systemctl is-active --quiet webtraffik.service; then
  systemctl restart webtraffik.service
  echo "  webtraffik : restarted"
else
  systemctl start webtraffik.service
  echo "  webtraffik : started"
fi

echo ""
echo "webTraffik installed and running."
echo "  status    : systemctl status webtraffik"
echo "  logs      : journalctl -u webtraffik -f"
echo "  dashboard : http://$(hostname -I | awk '{print $1}'):8999"
if [[ -n "${GENERATED_PASS:-}" ]]; then
  echo ""
  echo "  dashboard login (generated, stored in $CONFIG_DIR/dashboard.pass):"
  echo "    user: admin"
  echo "    pass: $GENERATED_PASS"
fi
