// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type captureBanEntry struct{ ExpiresAt uint64 }

type captureBanKey struct {
	SrcIp   [4]uint8
	DstPort uint16
	Pad     [2]uint8
}

// loadCapture returns the embedded CollectionSpec for capture.
func loadCapture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CaptureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load capture: %w", err)
	}

	return spec, err
}

// loadCaptureObjects loads capture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*captureObjects
//	*capturePrograms
//	*captureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCaptureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCapture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// captureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureSpecs struct {
	captureProgramSpecs
	captureMapSpecs
}

// captureSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureProgramSpecs struct {
	XdpCapture *ebpf.ProgramSpec `ebpf:"xdp_capture"`
}

// captureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureMapSpecs struct {
	BanMap          *ebpf.MapSpec `ebpf:"ban_map"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	MgmtAllowIpsMap *ebpf.MapSpec `ebpf:"mgmt_allow_ips_map"`
	MgmtPortsMap    *ebpf.MapSpec `ebpf:"mgmt_ports_map"`
	TelemetryMap    *ebpf.MapSpec `ebpf:"telemetry_map"`
}

// captureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureObjects struct {
	capturePrograms
	captureMaps
}

func (o *captureObjects) Close() error {
	return _CaptureClose(
		&o.capturePrograms,
		&o.captureMaps,
	)
}

// captureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureMaps struct {
	BanMap          *ebpf.Map `ebpf:"ban_map"`
	Events          *ebpf.Map `ebpf:"events"`
	MgmtAllowIpsMap *ebpf.Map `ebpf:"mgmt_allow_ips_map"`
	MgmtPortsMap    *ebpf.Map `ebpf:"mgmt_ports_map"`
	TelemetryMap    *ebpf.Map `ebpf:"telemetry_map"`
}

func (m *captureMaps) Close() error {
	return _CaptureClose(
		m.BanMap,
		m.Events,
		m.MgmtAllowIpsMap,
		m.MgmtPortsMap,
		m.TelemetryMap,
	)
}

// capturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type capturePrograms struct {
	XdpCapture *ebpf.Program `ebpf:"xdp_capture"`
}

func (p *capturePrograms) Close() error {
	return _CaptureClose(
		p.XdpCapture,
	)
}

func _CaptureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed capture_bpfeb.o
var _CaptureBytes []byte
