// Package ebpf provides the webTraffik eBPF XDP capture layer.
//
// It manages the full lifecycle of the XDP program: loading compiled bytecode,
// attaching to a network interface, syncing the ban map, reading connection
// events from the perf buffer, and exposing telemetry counters.
//
// The package supports three capture modes (see CaptureMode constants):
//   - ModeEBPFOnly: XDP handles all telemetry; no Go net.Listeners are spawned.
//   - ModeHybrid:   XDP enforces bans; Go listeners capture traffic and send
//     protocol banners. (default)
//   - ModeGoOnly:   eBPF is not used; pure userspace (current legacy behavior).
//
// # Build-time code generation
//
// The Go bindings for the compiled eBPF object are generated by bpf2go.
// Run `go generate ./internal/ebpf/...` (or `make ebpf-gen`) to regenerate
// after editing capture.bpf.c.
//
// Build requirements:
//   - clang >= 10
//   - llvm (for BPF target)
//   - linux-libc-dev or kernel headers
//
// Runtime requirements:
//   - Linux kernel >= 5.10
//   - CAP_BPF + CAP_NET_ADMIN (or root)

package ebpf

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -Wall -Wno-missing-declarations" capture bpf/programs/capture.bpf.c -- -I/usr/include/bpf -I/usr/include
