// SPDX-License-Identifier: GPL-2.0
//
// capture.bpf.c — webTraffik XDP capture program.
//
// Handles three concerns at the XDP layer:
//   1. Management port bypass: ports in mgmt_ports_map skip all logic.
//   2. Ban enforcement: packets from a banned {src_ip, dst_port} are dropped.
//   3. Telemetry: per-CPU passed/dropped counters + perf-event stream.
//
// Build requirements:
//   clang >= 10, linux-libc-dev, llvm (for BPF target)
//   Generated by: go generate ./internal/ebpf/... (via bpf2go)

#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/ipv6.h>
#include <linux/in.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include "../headers/bpf_helpers.h"
#include "../headers/bpf_endian.h"

#ifndef IPPROTO_ICMPV6
#define IPPROTO_ICMPV6 58
#endif

// ── Data structures ──────────────────────────────────────────────────────────

// All addresses are stored as 16 bytes in network order. IPv4 addresses are
// v4-mapped (::ffff:a.b.c.d) so one key layout serves both families.
struct ip_key {
    __u8 addr[16];
};

// ban_key: composite key for the ban map.
// dst_port is in network byte order (big-endian) to match packet headers.
struct ban_key {
    __u8  src_ip[16];
    __u16 dst_port;
    __u8  _pad[2];
};

// ban_entry: value stored in ban_map.
// expires_at is nanoseconds since boot (bpf_ktime_get_ns epoch).
struct ban_entry {
    __u64 expires_at;
};

// event: emitted to userspace via the perf event array (20 bytes).
// Emitted once per new TCP connection attempt (SYN without ACK), per UDP
// datagram and per ICMP/ICMPv6 packet — not per TCP segment — except packets
// shaped like replies to this host's own outbound traffic (see "Reply
// heuristics"); those are passed and counted but produce no event.
struct event {
    __u8  src_ip[16]; // v4-mapped or native IPv6, network order
    __u16 dst_port;   // host byte order
    __u8  dropped;    // 1 = XDP_DROP (banned), 0 = XDP_PASS
    __u8  protocol;   // IPPROTO_TCP (6), IPPROTO_UDP (17), ICMP (1) or ICMPv6 (58)
};

// ── eBPF Maps ────────────────────────────────────────────────────────────────

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 65536);
    __type(key, struct ban_key);
    __type(value, struct ban_entry);
} ban_map SEC(".maps");

// mgmt_ports_map: ports (host byte order) that bypass all eBPF logic.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 64);
    __type(key, __u16);
    __type(value, __u8);
} mgmt_ports_map SEC(".maps");

// mgmt_allow_ips_map: optional IP allowlist that bypasses bans.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 256);
    __type(key, struct ip_key);
    __type(value, __u8);
} mgmt_allow_ips_map SEC(".maps");

// telemetry_map: per-CPU packet disposition counters (0 = passed, 1 = dropped).
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 2);
    __type(key, __u32);
    __type(value, __u64);
} telemetry_map SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
} events SEC(".maps");

static __always_inline void telemetry_inc(__u32 idx) {
    __u64 *counter = bpf_map_lookup_elem(&telemetry_map, &idx);
    if (counter)
        __sync_fetch_and_add(counter, 1);
}

static __always_inline void emit(struct xdp_md *ctx, const __u8 *src,
                                 __u16 port, __u8 dropped, __u8 proto) {
    struct event ev = {};
    __builtin_memcpy(ev.src_ip, src, 16);
    ev.dst_port = port;
    ev.dropped  = dropped;
    ev.protocol = proto;
    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &ev, sizeof(ev));
}

// ── Reply heuristics ─────────────────────────────────────────────────────────
//
// The host's own outbound traffic (DNS lookups, NTP, apt, ping, traceroute...)
// draws replies from public IPs that look exactly like scans if reported.
// Without connection tracking we classify "reply-shaped" packets statelessly
// and suppress their *event* only: they are still passed, counted as passed
// and subject to ban enforcement, exactly as before.

// icmp4_is_reply: reply-class ICMPv4 types: 0 echo reply, 3 dest unreachable,
// 4 source quench, 5 redirect, 11 time exceeded, 12 parameter problem,
// 14/16/18 timestamp/info/mask replies. Echo request (8), timestamp request
// (13), info/mask requests (15/17) and unknown types are probes: reported.
static __always_inline int icmp4_is_reply(__u8 t) {
    switch (t) {
    case 0: case 3: case 4: case 5: case 11: case 12:
    case 14: case 16: case 18:
        return 1;
    }
    return 0;
}

// icmp6_is_reply: ICMPv6 errors (1-4), echo reply (129) and the link-local
// ND/MLD family (130-137). Echo request (128) is reported.
static __always_inline int icmp6_is_reply(__u8 t) {
    return (t >= 1 && t <= 4) || (t >= 129 && t <= 137);
}

// udp_is_reply: a datagram from a server-looking source port to a Linux
// ephemeral destination port (>= 32768). Source ports < 1024 are well-known
// services; 5353 (mDNS), 1900 (SSDP), 3478 (STUN), 4500 (IPsec NAT-T) and
// 5060 (SIP) are registered ports that count too, still only when
// dst >= 32768.
// Limits: this is a heuristic. A scanner that sources from a low port (e.g.
// UDP/53 or /123 reflection-style probes) to a high port of ours is missed
// (no event); a reply to a client socket bound to a non-ephemeral port
// (< 32768, e.g. 'dig -p 5300', or BSD/Windows ephemeral ranges) is still
// reported. Ports are host byte order.
static __always_inline int udp_is_reply(__u16 sport, __u16 dport) {
    if (dport < 32768)
        return 0;
    if (sport < 1024)
        return 1;
    return sport == 5353 || sport == 1900 || sport == 3478 ||
           sport == 4500 || sport == 5060;
}

// ── XDP entry point ──────────────────────────────────────────────────────────

SEC("xdp")
int xdp_capture(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;

    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end)
        return XDP_PASS;

    __u16 eth_proto = bpf_ntohs(eth->h_proto);
    struct ban_key bk = {};
    __u8 proto;
    void *l4;

    if (eth_proto == ETH_P_IP) {
        struct iphdr *ip = (void *)(eth + 1);
        if ((void *)(ip + 1) > data_end)
            return XDP_PASS;
        if (ip->ihl < 5)
            return XDP_PASS;
        // Multicast (224.0.0.0/4) and limited broadcast are LAN chatter
        // (mDNS, SSDP, LLMNR, DHCP…), never internet scanning: ignore.
        if ((bpf_ntohl(ip->daddr) & 0xf0000000) == 0xe0000000 ||
            ip->daddr == 0xffffffff)
            return XDP_PASS;
        proto = ip->protocol;
        l4 = (void *)ip + ip->ihl * 4;
        // v4-mapped: ::ffff:a.b.c.d
        bk.src_ip[10] = 0xff;
        bk.src_ip[11] = 0xff;
        __builtin_memcpy(&bk.src_ip[12], &ip->saddr, 4);
    } else if (eth_proto == ETH_P_IPV6) {
        struct ipv6hdr *ip6 = (void *)(eth + 1);
        if ((void *)(ip6 + 1) > data_end)
            return XDP_PASS;
        // IPv6 multicast (ff00::/8) is LAN chatter (mDNS, ND, MLD…): ignore.
        if (ip6->daddr.in6_u.u6_addr8[0] == 0xff)
            return XDP_PASS;
        // Extension headers are not walked: such packets pass untouched.
        proto = ip6->nexthdr;
        l4 = (void *)(ip6 + 1);
        __builtin_memcpy(bk.src_ip, &ip6->saddr, 16);
    } else {
        return XDP_PASS;
    }

    __u16 dst_port_net  = 0;
    __u16 dst_port_host = 0;
    int   new_conn      = 1; // whether this packet should produce an event

    if (proto == IPPROTO_TCP) {
        struct tcphdr *tcp = l4;
        if ((void *)(tcp + 1) > data_end)
            return XDP_PASS;
        dst_port_net  = tcp->dest;
        dst_port_host = bpf_ntohs(dst_port_net);
        new_conn = tcp->syn && !tcp->ack;
    } else if (proto == IPPROTO_UDP) {
        struct udphdr *udp = l4;
        if ((void *)(udp + 1) > data_end)
            return XDP_PASS;
        dst_port_net  = udp->dest;
        dst_port_host = bpf_ntohs(dst_port_net);
        new_conn = !udp_is_reply(bpf_ntohs(udp->source), dst_port_host);
    } else if (proto == IPPROTO_ICMP || proto == IPPROTO_ICMPV6) {
        __u8 *icmp_type = l4;
        if ((void *)(icmp_type + 1) > data_end)
            return XDP_PASS;
        telemetry_inc(0);
        int reply = proto == IPPROTO_ICMP ? icmp4_is_reply(*icmp_type)
                                          : icmp6_is_reply(*icmp_type);
        if (!reply)
            emit(ctx, bk.src_ip, 0, 0, proto);
        return XDP_PASS;
    } else {
        return XDP_PASS;
    }

    // Management port bypass: never banned or logged.
    if (bpf_map_lookup_elem(&mgmt_ports_map, &dst_port_host))
        return XDP_PASS;

    // Management IP bypass.
    struct ip_key ik = {};
    __builtin_memcpy(ik.addr, bk.src_ip, 16);
    if (bpf_map_lookup_elem(&mgmt_allow_ips_map, &ik))
        return XDP_PASS;

    // Ban check.
    bk.dst_port = dst_port_net;
    struct ban_entry *ban = bpf_map_lookup_elem(&ban_map, &bk);
    if (ban && bpf_ktime_get_ns() < ban->expires_at) {
        telemetry_inc(1);
        if (new_conn)
            emit(ctx, bk.src_ip, dst_port_host, 1, proto);
        return XDP_DROP;
    }

    telemetry_inc(0);
    if (new_conn)
        emit(ctx, bk.src_ip, dst_port_host, 0, proto);
    return XDP_PASS;
}

char LICENSE[] SEC("license") = "GPL";
