// SPDX-License-Identifier: GPL-2.0
//
// capture.bpf.c — webTraffik XDP capture program.
//
// Handles three concerns at the XDP layer:
//   1. Management port bypass: ports in mgmt_ports_map skip all logic.
//   2. Ban enforcement: packets from a banned {src_ip, dst_port} are dropped.
//   3. Telemetry: per-CPU passed/dropped counters + perf-event stream.
//
// Build requirements:
//   clang >= 10, linux-libc-dev, llvm (for BPF target)
//   Generated by: go generate ./internal/ebpf/... (via bpf2go)

#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/ipv6.h>
#include <linux/in.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include "../headers/bpf_helpers.h"
#include "../headers/bpf_endian.h"

#ifndef IPPROTO_ICMPV6
#define IPPROTO_ICMPV6 58
#endif

// ── Data structures ──────────────────────────────────────────────────────────

// All addresses are stored as 16 bytes in network order. IPv4 addresses are
// v4-mapped (::ffff:a.b.c.d) so one key layout serves both families.
struct ip_key {
    __u8 addr[16];
};

// ban_key: composite key for the ban map.
// dst_port is in network byte order (big-endian) to match packet headers.
struct ban_key {
    __u8  src_ip[16];
    __u16 dst_port;
    __u8  _pad[2];
};

// ban_entry: value stored in ban_map.
// expires_at is nanoseconds since boot (bpf_ktime_get_ns epoch).
struct ban_entry {
    __u64 expires_at;
};

// event: emitted to userspace via the perf event array (20 bytes).
// Emitted once per new TCP connection attempt (SYN without ACK), per UDP
// datagram and per ICMP/ICMPv6 packet — not per TCP segment.
struct event {
    __u8  src_ip[16]; // v4-mapped or native IPv6, network order
    __u16 dst_port;   // host byte order
    __u8  dropped;    // 1 = XDP_DROP (banned), 0 = XDP_PASS
    __u8  protocol;   // IPPROTO_TCP (6), IPPROTO_UDP (17), ICMP (1) or ICMPv6 (58)
};

// ── eBPF Maps ────────────────────────────────────────────────────────────────

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 65536);
    __type(key, struct ban_key);
    __type(value, struct ban_entry);
} ban_map SEC(".maps");

// mgmt_ports_map: ports (host byte order) that bypass all eBPF logic.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 64);
    __type(key, __u16);
    __type(value, __u8);
} mgmt_ports_map SEC(".maps");

// mgmt_allow_ips_map: optional IP allowlist that bypasses bans.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 256);
    __type(key, struct ip_key);
    __type(value, __u8);
} mgmt_allow_ips_map SEC(".maps");

// telemetry_map: per-CPU packet disposition counters (0 = passed, 1 = dropped).
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 2);
    __type(key, __u32);
    __type(value, __u64);
} telemetry_map SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
} events SEC(".maps");

static __always_inline void telemetry_inc(__u32 idx) {
    __u64 *counter = bpf_map_lookup_elem(&telemetry_map, &idx);
    if (counter)
        __sync_fetch_and_add(counter, 1);
}

static __always_inline void emit(struct xdp_md *ctx, const __u8 *src,
                                 __u16 port, __u8 dropped, __u8 proto) {
    struct event ev = {};
    __builtin_memcpy(ev.src_ip, src, 16);
    ev.dst_port = port;
    ev.dropped  = dropped;
    ev.protocol = proto;
    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &ev, sizeof(ev));
}

// ── XDP entry point ──────────────────────────────────────────────────────────

SEC("xdp")
int xdp_capture(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;

    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end)
        return XDP_PASS;

    __u16 eth_proto = bpf_ntohs(eth->h_proto);
    struct ban_key bk = {};
    __u8 proto;
    void *l4;

    if (eth_proto == ETH_P_IP) {
        struct iphdr *ip = (void *)(eth + 1);
        if ((void *)(ip + 1) > data_end)
            return XDP_PASS;
        if (ip->ihl < 5)
            return XDP_PASS;
        proto = ip->protocol;
        l4 = (void *)ip + ip->ihl * 4;
        // v4-mapped: ::ffff:a.b.c.d
        bk.src_ip[10] = 0xff;
        bk.src_ip[11] = 0xff;
        __builtin_memcpy(&bk.src_ip[12], &ip->saddr, 4);
    } else if (eth_proto == ETH_P_IPV6) {
        struct ipv6hdr *ip6 = (void *)(eth + 1);
        if ((void *)(ip6 + 1) > data_end)
            return XDP_PASS;
        // Extension headers are not walked: such packets pass untouched.
        proto = ip6->nexthdr;
        l4 = (void *)(ip6 + 1);
        __builtin_memcpy(bk.src_ip, &ip6->saddr, 16);
    } else {
        return XDP_PASS;
    }

    __u16 dst_port_net  = 0;
    __u16 dst_port_host = 0;
    int   new_conn      = 1; // whether this packet should produce an event

    if (proto == IPPROTO_TCP) {
        struct tcphdr *tcp = l4;
        if ((void *)(tcp + 1) > data_end)
            return XDP_PASS;
        dst_port_net  = tcp->dest;
        dst_port_host = bpf_ntohs(dst_port_net);
        new_conn = tcp->syn && !tcp->ack;
    } else if (proto == IPPROTO_UDP) {
        struct udphdr *udp = l4;
        if ((void *)(udp + 1) > data_end)
            return XDP_PASS;
        dst_port_net  = udp->dest;
        dst_port_host = bpf_ntohs(dst_port_net);
    } else if (proto == IPPROTO_ICMP || proto == IPPROTO_ICMPV6) {
        telemetry_inc(0);
        emit(ctx, bk.src_ip, 0, 0, proto);
        return XDP_PASS;
    } else {
        return XDP_PASS;
    }

    // Management port bypass: never banned or logged.
    if (bpf_map_lookup_elem(&mgmt_ports_map, &dst_port_host))
        return XDP_PASS;

    // Management IP bypass.
    struct ip_key ik = {};
    __builtin_memcpy(ik.addr, bk.src_ip, 16);
    if (bpf_map_lookup_elem(&mgmt_allow_ips_map, &ik))
        return XDP_PASS;

    // Ban check.
    bk.dst_port = dst_port_net;
    struct ban_entry *ban = bpf_map_lookup_elem(&ban_map, &bk);
    if (ban && bpf_ktime_get_ns() < ban->expires_at) {
        telemetry_inc(1);
        if (new_conn)
            emit(ctx, bk.src_ip, dst_port_host, 1, proto);
        return XDP_DROP;
    }

    telemetry_inc(0);
    if (new_conn)
        emit(ctx, bk.src_ip, dst_port_host, 0, proto);
    return XDP_PASS;
}

char LICENSE[] SEC("license") = "GPL";
