// SPDX-License-Identifier: GPL-2.0
//
// capture.bpf.c — webTraffik XDP capture program.
//
// Handles three concerns at the XDP layer:
//   1. Management port bypass: ports in mgmt_ports_map skip all logic.
//   2. Ban enforcement: packets from a banned {src_ip, dst_port} are dropped.
//   3. Telemetry: per-CPU passed/dropped counters + perf-event stream.
//
// Build requirements:
//   clang >= 10, linux-libc-dev, llvm (for BPF target)
//   Generated by: go generate ./internal/ebpf/... (via bpf2go)

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

// ── Constants ────────────────────────────────────────────────────────────────

#define ETH_P_IP   0x0800
#define ETH_P_IPV6 0x86DD

// ── Data structures ──────────────────────────────────────────────────────────

// ban_key: composite key for the ban map.
// IPv4 addresses are stored in the first 4 bytes; remaining bytes are zero.
// dst_port is in network byte order (big-endian) to match packet headers.
struct ban_key {
    __u8  src_ip[4];  // IPv4 address (network byte order)
    __u16 dst_port;   // destination port (network byte order)
    __u8  _pad[2];    // explicit padding for map key alignment
};

// ban_entry: value stored in ban_map.
// expires_at is nanoseconds since boot (bpf_ktime_get_ns epoch).
struct ban_entry {
    __u64 expires_at;
};

// event: emitted to userspace via the perf event array.
struct event {
    __u32 src_ip;    // IPv4 source address (host byte order)
    __u16 dst_port;  // destination port (host byte order)
    __u8  dropped;   // 1 = XDP_DROP (banned), 0 = XDP_PASS
    __u8  protocol;  // IPPROTO_TCP (6), IPPROTO_UDP (17), or IPPROTO_ICMP (1)
};

// ── eBPF Maps ────────────────────────────────────────────────────────────────

// ban_map: keyed by {src_ip, dst_port}; value is expiration timestamp.
// Populated by Go userspace on every ban/unban event.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 65536);
    __type(key, struct ban_key);
    __type(value, struct ban_entry);
} ban_map SEC(".maps");

// mgmt_ports_map: set of management ports that bypass all eBPF logic.
// Default contents: {8999, 22}. Populated at attach time from CLI flags.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 64);
    __type(key, __u16);   // port in host byte order
    __type(value, __u8);  // always 1 (set membership sentinel)
} mgmt_ports_map SEC(".maps");

// mgmt_allow_ips_map: optional additional IP allowlist for management access.
// Populated from -mgmt-allow-file at attach time and on SIGHUP reload.
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 256);
    __type(key, __u32);   // IPv4 address (host byte order)
    __type(value, __u8);  // always 1 (set membership sentinel)
} mgmt_allow_ips_map SEC(".maps");

// telemetry_map: per-CPU packet disposition counters.
// Index 0 = passed, index 1 = dropped.
// Per-CPU array means lock-free increments; Go aggregates across CPUs on read.
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 2);
    __type(key, __u32);
    __type(value, __u64);
} telemetry_map SEC(".maps");

// events: perf event array for streaming connection events to Go userspace.
// One slot per CPU; Go opens a perf.Reader for each CPU.
struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
} events SEC(".maps");

// ── Helper: increment a telemetry counter ───────────────────────────────────

static __always_inline void telemetry_inc(__u32 idx) {
    __u64 *counter = bpf_map_lookup_elem(&telemetry_map, &idx);
    if (counter)
        __sync_fetch_and_add(counter, 1);
}

// ── XDP entry point ──────────────────────────────────────────────────────────

SEC("xdp")
int xdp_capture(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;

    // ── 1. Parse Ethernet header ─────────────────────────────────────────────

    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end)
        return XDP_PASS;

    __u16 eth_proto = bpf_ntohs(eth->h_proto);

    // ── 2. Handle IPv4 only (skip IPv6 and other protocols) ──────────────────

    if (eth_proto != ETH_P_IP)
        return XDP_PASS;

    struct iphdr *ip = (void *)(eth + 1);
    if ((void *)(ip + 1) > data_end)
        return XDP_PASS;

    __u8 proto = ip->protocol;
    __u32 src_ip_net = ip->saddr;  // network byte order
    __u32 src_ip_host = bpf_ntohl(src_ip_net);

    // ── 3. Parse TCP or UDP to get the destination port ──────────────────────

    __u16 dst_port_net  = 0;  // network byte order
    __u16 dst_port_host = 0;  // host byte order

    if (proto == IPPROTO_TCP) {
        // ip->ihl gives the IP header length in 32-bit words
        struct tcphdr *tcp = (void *)ip + (ip->ihl * 4);
        if ((void *)(tcp + 1) > data_end)
            return XDP_PASS;
        dst_port_net  = tcp->dest;
        dst_port_host = bpf_ntohs(dst_port_net);
    } else if (proto == IPPROTO_UDP) {
        struct udphdr *udp = (void *)ip + (ip->ihl * 4);
        if ((void *)(udp + 1) > data_end)
            return XDP_PASS;
        dst_port_net  = udp->dest;
        dst_port_host = bpf_ntohs(dst_port_net);
    } else if (proto == IPPROTO_ICMP) {
        // ICMP — emit telemetry event with dst_port=0, then pass.
        // No ban or management-port check (ICMP has no port).
        telemetry_inc(0);

        struct event icmp_ev = {
            .src_ip   = src_ip_host,
            .dst_port = 0,
            .dropped  = 0,
            .protocol = proto,
        };
        bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU,
                              &icmp_ev, sizeof(icmp_ev));
        return XDP_PASS;
    } else {
        // Other protocols (IGMP, GRE, etc.) — pass without telemetry.
        return XDP_PASS;
    }

    // ── 4. Management port bypass ─────────────────────────────────────────────
    // Management ports (SSH=22, dashboard=8999) never get banned or logged.

    __u8 *is_mgmt_port = bpf_map_lookup_elem(&mgmt_ports_map, &dst_port_host);
    if (is_mgmt_port)
        return XDP_PASS;

    // ── 5. Management IP bypass ───────────────────────────────────────────────
    // Packets from explicitly allowed management IPs bypass bans.

    __u8 *is_mgmt_ip = bpf_map_lookup_elem(&mgmt_allow_ips_map, &src_ip_host);
    if (is_mgmt_ip)
        return XDP_PASS;

    // ── 6. Ban check ─────────────────────────────────────────────────────────

    struct ban_key bk = {};
    // Store IPv4 in first 4 bytes of src_ip field (network byte order).
    bk.src_ip[0] = (src_ip_net)       & 0xFF;
    bk.src_ip[1] = (src_ip_net >> 8)  & 0xFF;
    bk.src_ip[2] = (src_ip_net >> 16) & 0xFF;
    bk.src_ip[3] = (src_ip_net >> 24) & 0xFF;
    bk.dst_port  = dst_port_net;

    struct ban_entry *ban = bpf_map_lookup_elem(&ban_map, &bk);
    if (ban && bpf_ktime_get_ns() < ban->expires_at) {
        // Banned — drop and record telemetry.
        telemetry_inc(1);  // index 1 = dropped

        struct event ev = {
            .src_ip   = src_ip_host,
            .dst_port = dst_port_host,
            .dropped  = 1,
            .protocol = proto,
        };
        bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &ev, sizeof(ev));

        return XDP_DROP;
    }

    // ── 7. Allow — emit event and pass ───────────────────────────────────────

    telemetry_inc(0);  // index 0 = passed

    struct event ev = {
        .src_ip   = src_ip_host,
        .dst_port = dst_port_host,
        .dropped  = 0,
        .protocol = proto,
    };
    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &ev, sizeof(ev));

    return XDP_PASS;
}

char LICENSE[] SEC("license") = "GPL";
